<template>
  <div>
    <h3 class="title">Complete Company Information</h3>
    <h3><small>This are the information that will print on invoices and other important documents generated by system. Ensure contacts provided here are valid and handled by the authorised person</small></h3>

    <div class="alert alert-success" v-if="submitted">
                {{message}}
            </div>
    <form v-on:submit.prevent="companySetup">
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Business Name:</label>
            <input type="text" class="form-control" v-model="setup.business_name" name="business_name" v-validate="'required'">
            <div class="help-block alert alert-danger" v-show="errors.has('business_name')">
            {{errors.first('business_name')}}
            </div>
          </div>
        </div>
        </div>

        <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Business Address:</label>
            <input type="text" class="form-control" v-model="setup.business_address" name="business_name" v-validate="'required'">
            <div class="help-block alert alert-danger" v-show="errors.has('business_address')">
            {{errors.first('business_address')}}
            </div>
          </div>
        </div>
        </div>

        <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Phone Contact:</label>
            <input type="text" class="form-control" v-model="setup.contact_phone" name="business_name" v-validate="'required'">
            <div class="help-block alert alert-danger" v-show="errors.has('phone_contact')">
            {{errors.first('phone_contact')}}
            </div>
          </div>
        </div>
        </div>

        <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Contact E-Mail:</label>
            <input type="text" class="form-control" v-model="setup.contact_email" name="contact_email" v-validate="'required|email'">
            <div class="help-block alert alert-danger" v-show="errors.has('contact_email')">
            {{errors.first('contact_email')}}
            </div>
          </div>
        </div>
        </div>
        <!--
        <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Company Logo:</label>
            <input type="text" class="form-control" v-model="setup.company_logo" name="business_name" v-validate="'image'">
            <div class="help-block alert alert-danger" v-show="errors.has('company_logo')">
            {{errors.first('company_logo')}}
            </div>
          </div>
        </div>
        </div>
        -->

        <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <label>Tag Line:</label>
            <input type="text" class="form-control" v-model="setup.tag_line" name="business_name" v-validate="'required'">
            <div class="help-block alert alert-danger" v-show="errors.has('tag_line')">
            {{errors.first('tag_line')}}
            </div>
          </div>
        </div>
        </div>


         
          
          <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <button class="btn btn-info pull-right">Save</button>
            </div>
          </div>
        </div>
                 

       
    </form>
  </div>
</template>
<script>
  export default {
    data(){
        return{
          setup:{},
          message:'Company Setup was Successful, click the continue button to proceed!',
          submitted:false        }
    },
    methods: {
      companySetup(){
        let uri = 'http://127.0.0.1:8000/api/company/setup';
        this.$validator.validateAll().then(()=>
        {
        this.axios.post(uri, this.setup).then((response) => {
        this.submitted = true;
          //this.$router.push({name: 'list-categories'})
        })
        })
        
    }
  }
}
</script>